config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about' => 'pages#about'
  get '/thanks' => 'pages#thanks'
 
  get '/signup' => 'signups#new'
  post '/signup' => 'signups#create'
  
  resources :signups

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
  end
  
  def home
  end
  
  def about
  end
  
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  
  def new
    @signup = Signup.new()
  end
  
  def create
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to '/thanks'      
    else
      render 'new'
    end
  end
  
  private
  def signup_params
    params.require(:signup).permit(:firstname, :email)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  

  <%= csrf_meta_tags %>
</head>
  
<body>
<div class="wrapper">
  
  
  <div class="nav">
		<div class="container-fluid">
         <div class="row">
          <!-- Your content -->
          <ul>
            <li><%= link_to "Welcome", root_url %></li>
            <li><%= link_to "About", about_url %></li>
            <li><%= link_to "Sign-up Today", signup_url %></li>
          </ul>
      </div>
    </div>
</div>
  
  
  
<%= yield %>
  
  
<div class="footer">
  <div class="row">
    <div class="container">
      
      <h4> A Codeacademy project, completed by Lawrence G. </h4>
      
    </div>
  </div>
</div>
  
</div>
  
  
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
</body>
</html>

app/views/pages/about.html.erb
<div class="about-main">
  <div class="row">
    <div class="container">
      
      <h1>Here so you can relive your memories</h1>
      
      <%= link_to "Sign-up Today", signup_url, :class => "signup btn btn-primary" %>
      
    </div>
  </div>
</div>

<div class="about-supporting">
  <div class="row">
    <div class="container">
      
      <h2> No more sorting through photos </h2>
      
      <h3> Save time sorting through old photos, we'll pick the best ones so you can spend more time creating memories, not choosing which ones to keep. </h3>
      
      <%= link_to "Sign-up Today", signup_url, :class => "btn btn-primary" %>
      
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-main">
  <div class="row">
    <div class="container">
     
      <h1>Create and share your stories</h1>
      
      <%= link_to "Learn More", about_url,:id => "learnMoreMain", :class => "btn btn-primary " %>
      
    </div>
  </div>
</div>

<div class="home-supporting">
  <div class="row">
    <div class="container">
      
      <h2> Relive and share your adventures </h2>
      
      <h3> Stories creates a digital journal filled with only your best photos. </h3>
      
    </div>
  </div>
</div>

<div class="home-secondary">
  <div class="row">
    <div class="container">
      
      
      
    </div>
  </div>
</div>

<div class="home-discovery">
  <div class="row">
    <div class="container">
      
      <h1>Discover</h1>
      
      <%= link_to "Learn More", about_url, :class => "btn btn-primary" %>
      
    </div>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class="thanks-main">
  <div class="row">
    <div class="container">
     
      <h1>Thanks!</h1>
      
      <h3>We'll be in touch</h3>
      
    </div>
  </div>
</div>

app/views/signups/new.html.erb
<div class="new-main">
  <div class="row">
    <div class="container">
      
      <h1>Here so you can relive your memories</h1>
      
      <div class='forum'>
      <%= form_for(@signup) do |f| %>
      <%= f.text_field :firstname, :placeholder => "Insert First name" %>
      <%= f.email_field :email, :placeholder => "Insert Email" %>
      <%= f.submit "Add to mailing list", class: "btn btn-submit" %>
      <% end %>
      </div>
      
    </div>
  </div>
</div>